---
####
profiles:
 - profile::nginx::server
 - profile::world_temperatures::init


##### profile nginx
nginx::nginx_vhosts:
  blog:
    listen_port: 80
    use_default_location: false

nginx::nginx_locations:
  /:
    vhost: blog
    location_custom_cfg:
      proxy_pass: "http://localhost:3000"
      proxy_set_header:
        - 'Host              $http_host'
        - 'X-Forwarded-For   $proxy_add_x_forwarded_for'

